(function(){
const M=window.MV,E=window.MauvineEngine;
const out=[];const log=s=>{out.push(s);console.log(s)};let pass=0,fail=0;
const ok=(n,c,i)=>{c?pass++:fail++;log((c?'PASS ':'FAIL ')+n+(i!=null?' — '+i:''))};
fetch('../data/complete_data.json').then(r=>r.json()).then(o=>{
  const base=()=>{const ws=M.fromDataset(o,'inj');ws.scope={mode:'month',start:'2026-10-01',end:''};ws.goals=[];return ws};
  const solve=ws=>{const C=M.compile(ws);C.P.iters=40000;C.P.runs=1;return {C,r:E.solve(C.P)}};
  const team=(C,r,v)=>{const vis=C.map.visits[v],a=[];for(let z=vis.z0;z<vis.z0+vis.zn;z++)if(r.stats.active[z]&&r.seatP[z]>=0)a.push(C.map.people[r.seatP[z]]);return a};
  let ws=base();const ab=ws.people.find(p=>p.name==='أباظة'),am=ws.people.find(p=>p.roles.includes('r_clin'));
  const site=M.plannable(ws).find(s=>s.cat==='c_contracted');
  ws.goals=[M.mkGoal({kind:'inject',what:{k:'site',v:[site.id]},inject:{mode:'dates',dates:'2026-10-13'},who:{k:'person',v:[ab.id,am.id]},mode:'exact',hard:true})];
  let x=solve(ws);let vs=x.C.map.visits.map((v,i)=>i).filter(i=>x.C.map.visits[i].inj);
  const tm=team(x.C,x.r,vs[0]);ok('exact team = only chosen people',tm.length&&tm.every(p=>p===ab.id||p===am.id)&&tm.includes(ab.id)&&tm.includes(am.id),tm.join(','));
  ws=base();ws.goals=[M.mkGoal({kind:'inject',what:{k:'site',v:[site.id]},inject:{mode:'dates',dates:'2026-10-13'},who:{k:'role',v:['r_fin']},mode:'only',hard:true})];
  x=solve(ws);vs=x.C.map.visits.map((v,i)=>i).filter(i=>x.C.map.visits[i].inj);
  const fin=new Set(ws.people.filter(p=>p.roles.includes('r_fin')).map(p=>p.id));const t2=team(x.C,x.r,vs[0]);
  ok('only-from-group team',t2.length>0&&t2.every(p=>fin.has(p)),t2.length);
  ws=base();const locs=Array.from(new Set(M.plannable(ws).map(s=>s.loc)));const lc=locs.find(l=>{const n=M.plannable(ws).filter(s=>s.loc===l).length;return n>=2&&n<=4});
  const nIn=M.plannable(ws).filter(s=>s.loc===lc).length;
  ws.goals=[M.mkGoal({kind:'inject',what:{k:'loc',v:[lc]},inject:{mode:'pick',per:'each',op:'exact',n:1}})];
  x=solve(ws);const used=x.C.map.visits.map((v,i)=>i).filter(i=>x.C.map.visits[i].inj&&x.r.siteOf[i]>=0).map(i=>x.C.map.sites[x.r.siteOf[i]]);
  ok('each matching place once (pick)',used.length===nIn&&new Set(used).size===nIn,used.length+'/'+nIn);
  ws=base();const V0=M.compile(ws).P.V;ws.goals=[M.mkGoal({kind:'inject',what:{k:'site',v:[site.id]},inject:{mode:'dates',dates:'2026-10-13',add:'replace'}})];
  ok('replace keeps total visits',M.compile(ws).P.V===V0,M.compile(ws).P.V+' vs '+V0);
  ws=base();ws.goals=[M.mkGoal({kind:'inject',what:{k:'kmLe',v:'20'},inject:{mode:'pick',op:'between',n:2,n2:4}})];
  x=solve(ws);const n=x.C.map.visits.filter((v,i)=>v.inj&&x.r.siteOf[i]>=0).length;ok('pick between 2–4',n>=2&&n<=4,n);
  const g=M.normGoal(JSON.parse(JSON.stringify(ws.goals[0])));ok('inject roundtrip',g.inject.op==='between'&&g.inject.n2===4);
  log('\n'+pass+' passed, '+fail+' failed');document.getElementById('out').textContent=out.join('\n');
});
})();
